#!/bin/bash
# Copyright (c) 2025 Crash Override Inc.
# https://crashoverride.com
#
# SPDX-License-Identifier: GPL-3.0

#############################################################################
# Report Generator Library
# Generate security reports in various formats (Markdown, JSON, SARIF)
#############################################################################

# Source severity classifier for colors
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/severity-classifier.sh" 2>/dev/null || true

# Generate Markdown report
# Usage: generate_markdown_report <findings_json> <repo_name> <output_file>
generate_markdown_report() {
    local findings="$1"
    local repo_name="$2"
    local output_file="$3"
    local scan_date
    scan_date=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

    # Count findings by severity
    local critical high medium low total
    critical=$(echo "$findings" | jq '[.[] | select(.severity == "critical" or .severity == "CRITICAL")] | length')
    high=$(echo "$findings" | jq '[.[] | select(.severity == "high" or .severity == "HIGH")] | length')
    medium=$(echo "$findings" | jq '[.[] | select(.severity == "medium" or .severity == "MEDIUM")] | length')
    low=$(echo "$findings" | jq '[.[] | select(.severity == "low" or .severity == "LOW")] | length')
    total=$(echo "$findings" | jq 'length')

    cat > "$output_file" <<EOF
# Security Analysis Report

**Repository:** $repo_name
**Scan Date:** $scan_date
**Tool:** Gibson Powers Code Security Analyser

---

## Executive Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | $critical |
| 🟠 High | $high |
| 🟡 Medium | $medium |
| 🟢 Low | $low |
| **Total** | **$total** |

EOF

    # Add findings by category
    if [[ "$total" -gt 0 ]]; then
        cat >> "$output_file" <<EOF
---

## Findings

EOF

        # Group findings by severity
        for severity in critical high medium low; do
            local severity_findings
            severity_findings=$(echo "$findings" | jq --arg sev "$severity" '[.[] | select((.severity | ascii_downcase) == $sev)]')
            local count
            count=$(echo "$severity_findings" | jq 'length')

            if [[ "$count" -gt 0 ]]; then
                local icon
                case "$severity" in
                    critical) icon="🔴" ;;
                    high) icon="🟠" ;;
                    medium) icon="🟡" ;;
                    low) icon="🟢" ;;
                esac

                cat >> "$output_file" <<EOF
### $icon ${severity^} Severity ($count)

EOF

                # Output each finding
                echo "$severity_findings" | jq -r '.[] | @json' | while read -r finding; do
                    local file type line description cwe remediation code_snippet

                    file=$(echo "$finding" | jq -r '.file // "unknown"')
                    type=$(echo "$finding" | jq -r '.type // .category // "Security Issue"')
                    line=$(echo "$finding" | jq -r '.line // "N/A"')
                    description=$(echo "$finding" | jq -r '.description // "No description"')
                    cwe=$(echo "$finding" | jq -r '.cwe // "N/A"')
                    remediation=$(echo "$finding" | jq -r '.remediation // "No remediation provided"')
                    code_snippet=$(echo "$finding" | jq -r '.code_snippet // ""')

                    cat >> "$output_file" <<EOF
#### $type

- **File:** \`$file\`
- **Line:** $line
- **CWE:** $cwe

**Description:**
$description

EOF

                    if [[ -n "$code_snippet" && "$code_snippet" != "null" ]]; then
                        cat >> "$output_file" <<EOF
**Vulnerable Code:**
\`\`\`
$code_snippet
\`\`\`

EOF
                    fi

                    cat >> "$output_file" <<EOF
**Remediation:**
$remediation

---

EOF
                done
            fi
        done
    else
        cat >> "$output_file" <<EOF
✅ **No security vulnerabilities detected.**

The scan completed successfully without identifying any security issues.
EOF
    fi

    # Add footer
    cat >> "$output_file" <<EOF

---

*Generated by [Gibson Powers](https://github.com/crashappsec/gibson-powers) Code Security Analyser*
EOF
}

# Generate JSON report
# Usage: generate_json_report <findings_json> <repo_name> <output_file>
generate_json_report() {
    local findings="$1"
    local repo_name="$2"
    local output_file="$3"
    local scan_date
    scan_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Build report structure
    jq -n \
        --arg repo "$repo_name" \
        --arg date "$scan_date" \
        --arg tool "Gibson Powers Code Security Analyser" \
        --argjson findings "$findings" \
        '{
            metadata: {
                repository: $repo,
                scan_date: $date,
                tool: $tool,
                version: "1.0.0"
            },
            summary: {
                total: ($findings | length),
                critical: ([$findings[] | select(.severity == "critical" or .severity == "CRITICAL")] | length),
                high: ([$findings[] | select(.severity == "high" or .severity == "HIGH")] | length),
                medium: ([$findings[] | select(.severity == "medium" or .severity == "MEDIUM")] | length),
                low: ([$findings[] | select(.severity == "low" or .severity == "LOW")] | length)
            },
            findings: $findings
        }' > "$output_file"
}

# Generate SARIF report (GitHub code scanning compatible)
# Usage: generate_sarif_report <findings_json> <repo_name> <output_file>
generate_sarif_report() {
    local findings="$1"
    local repo_name="$2"
    local output_file="$3"

    jq -n \
        --arg repo "$repo_name" \
        --argjson findings "$findings" \
        '{
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            version: "2.1.0",
            runs: [{
                tool: {
                    driver: {
                        name: "Gibson Powers Code Security Analyser",
                        version: "1.0.0",
                        informationUri: "https://github.com/crashappsec/gibson-powers",
                        rules: [
                            ($findings | unique_by(.type) | map({
                                id: (.cwe // .type | gsub("[^a-zA-Z0-9-]"; "-")),
                                name: .type,
                                shortDescription: {
                                    text: .type
                                },
                                fullDescription: {
                                    text: (.description // .type)
                                },
                                defaultConfiguration: {
                                    level: (
                                        if (.severity | ascii_downcase) == "critical" then "error"
                                        elif (.severity | ascii_downcase) == "high" then "error"
                                        elif (.severity | ascii_downcase) == "medium" then "warning"
                                        else "note"
                                        end
                                    )
                                },
                                properties: {
                                    tags: [.category // "security"],
                                    precision: (.confidence // "medium"),
                                    "security-severity": (
                                        if (.severity | ascii_downcase) == "critical" then "9.0"
                                        elif (.severity | ascii_downcase) == "high" then "7.0"
                                        elif (.severity | ascii_downcase) == "medium" then "4.0"
                                        else "1.0"
                                        end
                                    )
                                }
                            }))[]
                        ]
                    }
                },
                results: [
                    ($findings | to_entries | map({
                        ruleId: (.value.cwe // .value.type | gsub("[^a-zA-Z0-9-]"; "-")),
                        ruleIndex: .key,
                        level: (
                            if (.value.severity | ascii_downcase) == "critical" then "error"
                            elif (.value.severity | ascii_downcase) == "high" then "error"
                            elif (.value.severity | ascii_downcase) == "medium" then "warning"
                            else "note"
                            end
                        ),
                        message: {
                            text: .value.description
                        },
                        locations: [{
                            physicalLocation: {
                                artifactLocation: {
                                    uri: .value.file,
                                    uriBaseId: "%SRCROOT%"
                                },
                                region: {
                                    startLine: (.value.line // 1)
                                }
                            }
                        }],
                        fixes: (
                            if .value.remediation then [{
                                description: {
                                    text: .value.remediation
                                }
                            }] else [] end
                        )
                    }))[]
                ]
            }]
        }' > "$output_file"
}

# Generate summary for console output
# Usage: print_summary <findings_json>
print_summary() {
    local findings="$1"

    local critical high medium low total
    critical=$(echo "$findings" | jq '[.[] | select(.severity == "critical" or .severity == "CRITICAL")] | length')
    high=$(echo "$findings" | jq '[.[] | select(.severity == "high" or .severity == "HIGH")] | length')
    medium=$(echo "$findings" | jq '[.[] | select(.severity == "medium" or .severity == "MEDIUM")] | length')
    low=$(echo "$findings" | jq '[.[] | select(.severity == "low" or .severity == "LOW")] | length')
    total=$(echo "$findings" | jq 'length')

    echo ""
    echo "════════════════════════════════════════════"
    echo "           SECURITY SCAN SUMMARY"
    echo "════════════════════════════════════════════"
    echo ""
    echo -e "  ${SEVERITY_COLORS[critical]:-}Critical:${NC:-} $critical"
    echo -e "  ${SEVERITY_COLORS[high]:-}High:${NC:-}     $high"
    echo -e "  ${SEVERITY_COLORS[medium]:-}Medium:${NC:-}   $medium"
    echo -e "  ${SEVERITY_COLORS[low]:-}Low:${NC:-}      $low"
    echo "  ──────────────────"
    echo "  Total:    $total"
    echo ""
}

# Generate report in specified format
# Usage: generate_report <format> <findings_json> <repo_name> <output_dir>
generate_report() {
    local format="$1"
    local findings="$2"
    local repo_name="$3"
    local output_dir="$4"

    mkdir -p "$output_dir"

    case "$format" in
        markdown|md)
            generate_markdown_report "$findings" "$repo_name" "$output_dir/security-report.md"
            echo "$output_dir/security-report.md"
            ;;
        json)
            generate_json_report "$findings" "$repo_name" "$output_dir/security-report.json"
            echo "$output_dir/security-report.json"
            ;;
        sarif)
            generate_sarif_report "$findings" "$repo_name" "$output_dir/security-report.sarif"
            echo "$output_dir/security-report.sarif"
            ;;
        all)
            generate_markdown_report "$findings" "$repo_name" "$output_dir/security-report.md"
            generate_json_report "$findings" "$repo_name" "$output_dir/security-report.json"
            generate_sarif_report "$findings" "$repo_name" "$output_dir/security-report.sarif"
            echo "$output_dir"
            ;;
        *)
            echo "Unknown format: $format" >&2
            return 1
            ;;
    esac
}
