run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - durationcheck
    - makezero
    - rowserrcheck
    - sqlclosecheck
    - unconvert
  # Disabled linters (too noisy for now, will enable gradually):
  # - contextcheck  # Many valid uses of context.Background() in goroutines
  # - errorlint     # Type assertions on errors are valid in many cases
  # - nilerr        # Many intentional patterns in filepath.Walk callbacks
  # - noctx         # HTTP requests without context are acceptable in CLI tools
  # - predeclared   # Using min/max/new as names is common
  # - unparam       # Unused params kept for API consistency
  # - exportloopref # Deprecated in Go 1.22+

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gosec:
    excludes:
      - G104 # Audit errors not checked - we have specific handlers
      - G304 # File path provided as taint input - we validate paths
  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - stringintconv
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unusedresult
    # shadow checking disabled - too noisy and often intentional

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gosimple
        - staticcheck
        - ineffassign
    # Exclude known patterns
    - linters:
        - errcheck
      text: "Error return value of .*(Close|Write|Flush)"
  max-issues-per-linter: 50
  max-same-issues: 10
