// Package report provides shared report generation utilities
package report

import (
	"fmt"
	"strings"
)

// ReportBuilder provides fluent API for markdown report generation
type ReportBuilder struct {
	sb strings.Builder
}

// NewBuilder creates a new report builder
func NewBuilder() *ReportBuilder {
	return &ReportBuilder{}
}

// Title adds a level-1 heading
func (b *ReportBuilder) Title(title string) *ReportBuilder {
	b.sb.WriteString(fmt.Sprintf("# %s\n\n", title))
	return b
}

// Meta adds report metadata section
func (b *ReportBuilder) Meta(meta ReportMeta) *ReportBuilder {
	b.sb.WriteString(fmt.Sprintf("**Repository:** `%s`\n", meta.Repository))
	b.sb.WriteString(fmt.Sprintf("**Generated:** %s\n", meta.Timestamp.Format("2006-01-02 15:04:05 UTC")))
	if meta.ScannerDesc != "" {
		b.sb.WriteString(fmt.Sprintf("**Scanner:** %s\n", meta.ScannerDesc))
	}
	b.sb.WriteString("\n---\n\n")
	return b
}

// Section adds a section heading at the specified level (1-6)
func (b *ReportBuilder) Section(level int, title string) *ReportBuilder {
	if level < 1 {
		level = 1
	}
	if level > 6 {
		level = 6
	}
	prefix := strings.Repeat("#", level)
	b.sb.WriteString(fmt.Sprintf("%s %s\n\n", prefix, title))
	return b
}

// Table adds a markdown table
func (b *ReportBuilder) Table(headers []string, rows [][]string) *ReportBuilder {
	if len(headers) == 0 {
		return b
	}

	// Header row
	b.sb.WriteString("|")
	for _, h := range headers {
		b.sb.WriteString(fmt.Sprintf(" %s |", h))
	}
	b.sb.WriteString("\n|")

	// Separator row
	for range headers {
		b.sb.WriteString("--------|")
	}
	b.sb.WriteString("\n")

	// Data rows
	for _, row := range rows {
		b.sb.WriteString("|")
		for i := range headers {
			cell := ""
			if i < len(row) {
				cell = row[i]
			}
			b.sb.WriteString(fmt.Sprintf(" %s |", cell))
		}
		b.sb.WriteString("\n")
	}
	b.sb.WriteString("\n")
	return b
}

// Paragraph adds a paragraph of text
func (b *ReportBuilder) Paragraph(text string) *ReportBuilder {
	b.sb.WriteString(text)
	b.sb.WriteString("\n\n")
	return b
}

// List adds a bulleted list
func (b *ReportBuilder) List(items []string) *ReportBuilder {
	for _, item := range items {
		b.sb.WriteString(fmt.Sprintf("- %s\n", item))
	}
	b.sb.WriteString("\n")
	return b
}

// NumberedList adds a numbered list
func (b *ReportBuilder) NumberedList(items []string) *ReportBuilder {
	for i, item := range items {
		b.sb.WriteString(fmt.Sprintf("%d. %s\n", i+1, item))
	}
	b.sb.WriteString("\n")
	return b
}

// CodeBlock adds a fenced code block
func (b *ReportBuilder) CodeBlock(lang, code string) *ReportBuilder {
	b.sb.WriteString(fmt.Sprintf("```%s\n%s\n```\n\n", lang, code))
	return b
}

// Quote adds a blockquote
func (b *ReportBuilder) Quote(text string) *ReportBuilder {
	lines := strings.Split(text, "\n")
	for _, line := range lines {
		b.sb.WriteString(fmt.Sprintf("> %s\n", line))
	}
	b.sb.WriteString("\n")
	return b
}

// Divider adds a horizontal rule
func (b *ReportBuilder) Divider() *ReportBuilder {
	b.sb.WriteString("---\n\n")
	return b
}

// Bold wraps text in bold markers
func (b *ReportBuilder) Bold(text string) string {
	return fmt.Sprintf("**%s**", text)
}

// Italic wraps text in italic markers
func (b *ReportBuilder) Italic(text string) string {
	return fmt.Sprintf("*%s*", text)
}

// Code wraps text in inline code markers
func (b *ReportBuilder) Code(text string) string {
	return fmt.Sprintf("`%s`", text)
}

// Link creates a markdown link
func (b *ReportBuilder) Link(text, url string) string {
	return fmt.Sprintf("[%s](%s)", text, url)
}

// KeyValue adds a key-value pair on its own line
func (b *ReportBuilder) KeyValue(key, value string) *ReportBuilder {
	b.sb.WriteString(fmt.Sprintf("**%s:** %s\n", key, value))
	return b
}

// Raw adds raw text without formatting
func (b *ReportBuilder) Raw(text string) *ReportBuilder {
	b.sb.WriteString(text)
	return b
}

// Newline adds a newline
func (b *ReportBuilder) Newline() *ReportBuilder {
	b.sb.WriteString("\n")
	return b
}

// Footer adds a standard footer
func (b *ReportBuilder) Footer(scanner string) *ReportBuilder {
	b.sb.WriteString("---\n\n")
	b.sb.WriteString(fmt.Sprintf("*Generated by Zero %s Scanner*\n", scanner))
	return b
}

// String returns the built report as a string
func (b *ReportBuilder) String() string {
	return b.sb.String()
}

// Bytes returns the built report as bytes
func (b *ReportBuilder) Bytes() []byte {
	return []byte(b.sb.String())
}

// Reset clears the builder for reuse
func (b *ReportBuilder) Reset() *ReportBuilder {
	b.sb.Reset()
	return b
}

// Len returns the current length of the built content
func (b *ReportBuilder) Len() int {
	return b.sb.Len()
}
