# Semgrep Default Profile
# Balanced scanning for tech discovery, secrets, and basic security
#
# Usage: semgrep-scanner.sh <repo>  (uses this profile by default)

profile:
  name: default
  description: Balanced scanning for technology discovery and basic security

sources:
  # Gibson custom rules
  custom:
    - tech-discovery.yaml    # Technology identification
    - secrets.yaml           # Secret detection
    - tech-debt.yaml         # TODO/FIXME markers

  # Minimal community rules for speed
  community:
    - p/secrets              # Secret detection
    - p/security-audit       # Basic security audit

severity:
  minimum: WARNING
  fail_on: ERROR

confidence:
  minimum: MEDIUM

output:
  format: json
  include_git_blame: true
  group_by: category
  max_findings: 500

performance:
  timeout_per_file: 15
  max_memory: 2048
  jobs: auto

exclude:
  paths:
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/.git/**"
    - "**/dist/**"
    - "**/build/**"
