name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps improve Gibson Powers for everyone.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: When I run the DORA metrics analyzer, it fails with...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command `./dora-analyzer.sh ...`
        2. With these parameters `...`
        3. Error occurs when...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The analyzer should generate a report showing...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, it crashes with error...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which Gibson Powers component is affected?
      options:
        - DORA Metrics
        - Code Ownership
        - Supply Chain Analysis
        - Certificate Analyzer
        - Chalk Build Analyzer
        - Package Health Analyzer
        - Prompts/Templates
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: Tier
      description: Which tier are you using?
      options:
        - "Tier 1: Standalone Scripts"
        - "Tier 2: AI-Enhanced (Claude)"
        - "Tier 3: Platform-Powered"
        - Not sure
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Shell: [e.g., bash 5.2, zsh]
        - Git version: [e.g., 2.40.0]
        - Claude Code version: [if using Tier 2]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Output
      description: Please paste any relevant error messages or output
      placeholder: |
        Error: Command failed...
        Stack trace...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This started happening after...
    validations:
      required: false
