# Malcontent Default Profile
# Standard analysis for supply chain compromise detection
#
# Usage: malcontent.sh <repo>  (uses this profile by default)

profile:
  name: default
  description: Standard analysis with balanced risk threshold

settings:
  mode: analyze
  min_risk: medium
  format: json

# File types to analyze
include:
  # Binaries
  - "**/*.so"
  - "**/*.dylib"
  - "**/*.dll"
  - "**/*.exe"
  # Scripts
  - "**/*.sh"
  - "**/*.bash"
  - "**/*.py"
  - "**/*.rb"
  - "**/*.js"
  - "**/*.go"
  # Config that might run code
  - "**/Makefile"
  - "**/Dockerfile"
  - "**/.github/workflows/*.yml"
  - "**/.gitlab-ci.yml"

# Paths to exclude from analysis
exclude:
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/.git/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/__pycache__/**"

# Risk thresholds
thresholds:
  # Alert on these risk levels
  alert_on:
    - critical
    - high
    - medium
  # Fail on these risk levels (for CI/CD)
  fail_on:
    - critical

# Behaviors to flag (subset of malcontent capabilities)
behaviors:
  critical:
    - backdoor
    - rootkit
    - keylogger
    - ransomware
    - cryptominer
    - c2_communication
  high:
    - shell_execution
    - process_injection
    - credential_theft
    - network_exfiltration
    - persistence_mechanism
  medium:
    - obfuscation
    - anti_debugging
    - privilege_escalation
    - system_modification

output:
  format: json
  include_details: true
  max_findings: 500
