#!/bin/bash
# Compare Base vs AI-Enhanced Analyzers
# Copyright (c) 2024 Gibson Powers Contributors
# SPDX-License-Identifier: GPL-3.0

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default values
REPO=""
ORG=""
SBOM_FILE=""
OUTPUT_FILE=""

# Usage
usage() {
    cat <<EOF
Compare Package Health Analyzers

Runs both base and AI-enhanced analyzers and compares their outputs.

Usage: $0 [OPTIONS]

OPTIONS:
    --repo OWNER/REPO          Compare analysis of single repository
    --org ORGANIZATION         Compare analysis of organization
    --sbom FILE                Compare analysis of existing SBOM
    --output FILE              Write comparison to file (default: stdout)
    -h, --help                 Show this help message

EXAMPLES:
    $0 --repo owner/repo
    $0 --org myorg --output comparison.md

EOF
    exit 0
}

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --repo)
                REPO="$2"
                shift 2
                ;;
            --org)
                ORG="$2"
                shift 2
                ;;
            --sbom)
                SBOM_FILE="$2"
                shift 2
                ;;
            --output)
                OUTPUT_FILE="$2"
                shift 2
                ;;
            -h|--help)
                usage
                ;;
            *)
                echo "Error: Unknown option: $1" >&2
                usage
                ;;
        esac
    done
}

# Run base analyzer
run_base() {
    local args=$1

    echo "Running base analyzer..." >&2

    local start_time=$(date +%s)
    local result=$("$SCRIPT_DIR/package-health-analyzer.sh" $args --format json 2>/dev/null)
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))

    echo "$result" | jq --argjson duration "$duration" '. + {execution_time_seconds: $duration}'
}

# Run AI-enhanced analyzer
run_ai() {
    local args=$1

    echo "Running AI-enhanced analyzer..." >&2

    if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
        echo "Warning: ANTHROPIC_API_KEY not set, skipping AI analysis" >&2
        echo '{"error": "api_key_not_set"}'
        return 1
    fi

    local start_time=$(date +%s)
    local result=$("$SCRIPT_DIR/package-health-analyzer-claude.sh" $args --format json 2>/dev/null)
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))

    echo "$result" | jq --argjson duration "$duration" '.base_analysis.execution_time_seconds = $duration | .'
}

# Generate comparison report
generate_comparison() {
    local base_result=$1
    local ai_result=$2

    cat <<EOF
# Package Health Analyzer Comparison

**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Performance Comparison

| Analyzer       | Execution Time | Packages Analyzed | Issues Found |
|----------------|----------------|-------------------|--------------|
| Base           | $(echo "$base_result" | jq -r '.execution_time_seconds // 0')s | $(echo "$base_result" | jq -r '.summary.total_packages // 0') | $(echo "$base_result" | jq -r '.summary.deprecated_packages + .summary.low_health_packages // 0') |
| AI-Enhanced    | $(echo "$ai_result" | jq -r '.base_analysis.execution_time_seconds // 0')s | $(echo "$ai_result" | jq -r '.base_analysis.summary.total_packages // 0') | $(echo "$ai_result" | jq -r '.base_analysis.summary.deprecated_packages + .base_analysis.summary.low_health_packages // 0') |

## Feature Comparison

### Base Analyzer
- ✓ Fast automated scanning
- ✓ Health scoring
- ✓ Deprecation detection
- ✓ Version inconsistency analysis
- ✗ No contextual recommendations
- ✗ No migration guidance
- ✗ No risk prioritization

### AI-Enhanced Analyzer
- ✓ All base analyzer features
- ✓ Chain of reasoning (integrates vulnerability & provenance data)
- ✓ Contextual risk assessment
- ✓ Detailed migration strategies
- ✓ Alternative package recommendations
- ✓ Prioritized action plans
- ✓ Strategic operational recommendations

## Common Findings

### Deprecated Packages
$(echo "$base_result" | jq -r '
    .packages[] |
    select(.deprecation.deprecated == true) |
    "- \(.package) v\(.version)"
' | head -10)

### Low Health Packages
$(echo "$base_result" | jq -r '
    .packages[] |
    select(.health_score < 60) |
    "- \(.package) v\(.version): Score \(.health_score) (\(.health_grade))"
' | head -10)

## AI-Enhanced Insights

$(echo "$ai_result" | jq -r '.ai_analysis // "Not available"' | head -100)

...

## Recommendations

### When to Use Base Analyzer
- Quick automated scans
- CI/CD pipeline integration
- Regular monitoring
- When API quotas are a concern

### When to Use AI-Enhanced Analyzer
- Comprehensive audits
- Migration planning
- Risk assessment
- Strategic decision making
- When detailed recommendations are needed

## Raw Data

<details>
<summary>View Complete Base Analysis</summary>

\`\`\`json
$(echo "$base_result" | jq '.')
\`\`\`

</details>

---

*Comparison generated by Package Health Analyzer*
EOF
}

# Main execution
main() {
    parse_args "$@"

    # Validate input
    if [ -z "$REPO" ] && [ -z "$ORG" ] && [ -z "$SBOM_FILE" ]; then
        echo "Error: Must specify --repo, --org, or --sbom" >&2
        usage
    fi

    # Prepare arguments
    local args=""
    if [ -n "$REPO" ]; then
        args="--repo $REPO"
    elif [ -n "$ORG" ]; then
        args="--org $ORG"
    elif [ -n "$SBOM_FILE" ]; then
        args="--sbom $SBOM_FILE"
    fi

    # Run both analyzers
    local base_result=$(run_base "$args")
    local ai_result=$(run_ai "$args")

    # Generate comparison
    local comparison=$(generate_comparison "$base_result" "$ai_result")

    # Output
    if [ -n "$OUTPUT_FILE" ]; then
        echo "$comparison" > "$OUTPUT_FILE"
        echo "✓ Comparison complete. Report saved to: $OUTPUT_FILE"
    else
        echo "$comparison"
    fi
}

# Run main
main "$@"
